export const FETCH_PROBLEMS = 'FETCH_PROBLEMS';
export const FETCH_PROBLEMS_START = 'FETCH_PROBLEMS_START';
export const FETCH_PROBLEMS_FINISH = 'FETCH_PROBLEMS_FINISH';
export const FETCH_PROBLEMS_ERROR = 'FETCH_PROBLEMS_ERROR';

export const SELECTE_PROBLEM = 'SELECTE_PROBLEM';
export const SELECTED_PROBLEM = 'SELECTED_PROBLEM';
