export const FETCH_PROBLEMS = 'FETCH_PROBLEMS';
export const FETCH_PROBLEMS_START = 'FETCH_PROBLEMS_START';
export const FETCH_PROBLEMS_FINISH = 'FETCH_PROBLEMS_FINISH';
export const FETCH_PROBLEMS_ERROR = 'FETCH_PROBLEMS_ERROR';

export const REFETCH_PROBLEMS = 'REFETCH_PROBLEMS';

export const FETCH_ALL_PROBLEMS = 'FETCH_ALL_PROBLEMS';
export const FETCH_ALL_PROBLEMS_START = 'FETCH_ALL_PROBLEMS_START';
export const FETCH_ALL_PROBLEMS_FINISH = 'FETCH_ALL_PROBLEMS_FINISH';
export const FETCH_ALL_PROBLEMS_ERROR = 'FETCH_ALL_PROBLEMS_ERROR';

export const REFETCH_ALL_PROBLEMS = 'REFETCH_ALL_PROBLEMS';

export const SELECT_PROBLEM = 'SELECT_PROBLEM';
export const FETCH_SELECT_PROBLEM_RESPONSES = 'FETCH_SELECT_PROBLEM_RESPONSES';
export const FETCH_SELECT_PROBLEM_RESPONSES_START = 'FETCH_SELECT_PROBLEM_RESPONSES_START';
export const FETCH_SELECT_PROBLEM_RESPONSES_FINISH = 'FETCH_SELECT_PROBLEM_RESPONSES_FINISH';
export const FETCH_SELECT_PROBLEM_RESPONSES_ERROR = 'FETCH_SELECT_PROBLEM_RESPONSES_ERROR';

export const FETCH_MY_RESPONSES_PROBLEMS = 'FETCH_MY_RESPONSES_PROBLEMS';
export const FETCH_MY_RESPONSES_PROBLEMS_START = 'FETCH_MY_RESPONSES_PROBLEMS_START';
export const FETCH_MY_RESPONSES_PROBLEMS_FINISH = 'FETCH_MY_RESPONSES_PROBLEMS_FINISH';
export const FETCH_MY_RESPONSES_PROBLEMS_ERROR = 'FETCH_MY_RESPONSES_PROBLEMS_ERROR';

export const REFETCH_MY_RESPONSES_PROBLEMS = 'REFETCH_MY_RESPONSES_PROBLEMS';

export const SAW_RESPONSES_OF_PROBLEM = 'SAW_RESPONSES_OF_PROBLEM';
