export const FETCH_PROBLEMS = 'FETCH_PROBLEMS';
export const FETCH_PROBLEMS_START = 'FETCH_PROBLEMS_START';
export const FETCH_PROBLEMS_FINISH = 'FETCH_PROBLEMS_FINISH';
export const FETCH_PROBLEMS_ERROR = 'FETCH_PROBLEMS_ERROR';

export const REFETCH_PROBLEMS = 'REFETCH_PROBLEMS';

export const SELECT_PROBLEM = 'SELECT_PROBLEM';

export const SAW_RESTPONSES_OF_PROBLEM = 'SAW_RESTPONSES_OF_PROBLEM';
